src/app/globals.css, tailwind.config.ts
- tailwind.config.ts 파일에 font, font-size, color 테마 생성
- globals.css 파일에 font 추가
=> [design] 폰트, 색상, 폰트 사이즈 테마 생성

src/components/common/Footer.tsx
| 완성 이미지/GIF |
| <img src='https://github.com/Woongjin-Udemy-Pixe11/sturing/assets/91606951/92acc4bd-fc84-4a3c-837a-3ac9770de046' />  |
- 푸터 컴포넌트 완료했습니다.
=> [design] Footer 컴포넌트 생성

src/app/page.tsx, src/components/common/Card.tsx
| 완성 이미지/GIF |
| <img width="140" alt="image" src="https://github.com/Woongjin-Udemy-Pixe11/sturing/assets/56349582/17aed9a6-99b1-49b0-8ea3-b498f3c9c5ac">  |
- 북마크 아이콘 추가
- 클릭했을때 on/off 처리
- 북마크 아이콘 클릭했을때 이미지 내부 "스터디 시간 미정" 텍스트에는 select-none처리 해뒀습니다!
1. 북마크 아이콘 클릭시 아래 텍스트에도 드래그 처리? 되는 경우 있는데 
이런 부분까지는 추후에 기본기능 구현 끝나고 한번 살펴보고 수정해야할것 같습니다.
=> [design] Card 컴포넌트 북마크 추가

src/components/common/Complete.tsx, src/components/common/LongButton.tsx, src/components/common/StudyForm.tsx
| 완성 이미지/GIF |
| StudyForm.tsx | Complete.tsx | LongButton.tsx |
| :-------------: | :-------------: | :-------------: |
| <img width="250" alt="스크린샷 2024-06-26 오후 1 50 34" src="https://github.com/Woongjin-Udemy-Pixe11/sturing/assets/139545377/d83d66e7-8d95-40d9-8c75-248a2399325c"> | <img width="250" alt="스크린샷 2024-06-26 오후 1 51 48" src="https://github.com/Woongjin-Udemy-Pixe11/sturing/assets/139545377/b86585f0-fbd3-4a28-8d57-9b2726083021">  | <img width="200" alt="스크린샷 2024-06-26 오후 1 52 42" src="https://github.com/Woongjin-Udemy-Pixe11/sturing/assets/139545377/4ffc0072-9334-4836-842d-867254b9eb8e">
- `StudyForm` 컴포넌트에서 각각 해당하는 내용을 넣으면 됩니다.
- `Complete`에서 `heading`은 제목, `subheading` 들어가는 내용을 적으시면 됩니다.
- `LongButton`  color를 blue, gray, white, red로 각각 만들어둬서 color …
=> [design] 스터디 폼, 완료페이지, 긴버튼 공통 컴포넌트 생성

src/components/sidebar/SideBar.tsx, src/components/sidebar/SideBarToggle.tsx, src/components/sidebar/UserProfile.tsx
| 로그인 전 | 로그인 후 |
| :-------------: | :-------------: |
| <img src='https://github.com/Woongjin-Udemy-Pixe11/sturing/assets/91606951/d067723c-4a4f-4f22-8e2d-91563318123b' />  |<img src='https://github.com/Woongjin-Udemy-Pixe11/sturing/assets/91606951/f402a953-494e-4e39-9ab8-13873663b1d1' />  |
- Header.tsx에서 토글 기능은 아직 구현하지 않았습니다.
- 스크롤바가 생기는 위치는 현재 고민중입니다.
=> [design] 사이드바 퍼블리싱 완료

tailwind.config.ts
=> [design] 모달 관련 boxshadow 추가, 캘린더 관연 color accent 추가

src/app/users/[userid]/_componets/MiniAgreeModal.tsx, src/app/users/[userid]/_pages/MyBookMarkList.tsx, src/app/users/[userid]/page.tsx
| 완성 이미지/GIF |
|  
|
-  탈퇴동의 컴포넌트 약 반응형
1. 진짜 반응형을 구현하려면 어떻게 디자인하면좋을까?
2. 로고가있는 공통 헤더를 모든페이지 상단에 위치하게하면 어떨까? (layout)에 작성
=> [desing] 마이페이지 컴포넌트 간단 반응형 추가

src/app/(공용작업)/test/_componet/CollectStudyClient.tsx, src/app/(공용작업)/test/_componet/SelectCateGory.tsx, src/app/(공용작업)/test/page.tsx, src/components/common/LongButton.tsx, src/constant/searchLabelList.ts
| 완성 이미지/GIF |
|![image](https://github.com/Woongjin-Udemy-Pixe11/sturing/assets/124956289/0296f777-1683-4b6c-96fc-c09327ccb900)  |
- 모집글 컴포넌트 퍼블리싱 완료
- LongButton props ClassName 추가
- className 동적으로 받아서 사용할수있게 컴포넌트 변경했습니다. 입력안해도 상관없는 속성이라 기존컴포넌트 변경은 안해도됩니다.
1.
=> [design] LongButton Componet ClassName 받아서 사용, 분야선택 컴포넌트 완성

src/app/(JH)/users/[userid]/_pages/MyPage.tsx, src/app/(JH)/users/[userid]/detail/page.tsx, src/app/(JH)/users/[userid]/mybookmark/page.tsx, src/app/(JH)/users/[userid]/mystudylog/page.tsx, src/app/(JH)/users/[userid]/mystudyreview/page.tsx, src/app/(JH)/users/[userid]/page.tsx, src/app/(공용작업)/my-study-main/layout.tsx, src/app/layout.tsx, src/components/(JH)/matching/MatchingFooter.tsx, src/components/(JH)/users/MyStudyInfo.tsx, src/components/(JH)/users/UserMatchingInfo.tsx, src/components/(suwan)/my-study/common/Header.tsx
| 완성 이미지/GIF |
- 기존 페이지에서 링크
- 내스터디상세정보에서 Header layout-client 컴포넌트로 1차처리
1. layout 부분 추후 서버컴포넌트 혹은 Header만 Client 로 빼서 처리할것인가?
=> [feat] 마이페이지 Link 연결 및 내스터디정보 layout 변경처리

src/app/(공용작업)/my-study-main/board/_component/NoticeBoardDetail.tsx, src/app/(공용작업)/my-study-main/board/_component/NoticeBoardList.tsx, src/app/(공용작업)/my-study-main/board/_component/TaskBoardList.tsx, src/app/(공용작업)/my-study-main/board/notice-board/write/page.tsx, src/app/(공용작업)/my-study-main/board/task-board/write/page.tsx, src/components/(suwan)/my-study/calendar/Schedule.tsx, src/components/(suwan)/my-study/common/Calendar.tsx, src/components/(suwan)/my-study/my-todo/MyTodoContainer.tsx, src/components/(suwan)/my-study/my-todo/Todos.tsx, src/components/(yejin)/my-study/ApplicationList.tsx, src/components/(yejin)/my-study/UpcomingStudy.tsx, src/components/common/calender/ui/calendar.tsx, src/components/main/TabBar.tsx
=> [design] 공지사항, 게시판, 달력 부분 디자인 수정

src/app/(JH)/users/[userid]/_pages/MyBookMarkList.tsx, src/app/(jisubin)/lectureDetail/study/page.tsx, src/app/(공용작업)/make-study-form/_component/StudyDetailInfoForm.tsx, src/components/common/Card.tsx, src/components/search/StudyList.tsx
=> [design] Card Componet 반응형 수정

src/app/(공용작업)/my-study-main/board/_component/NoticeBoardDetail.tsx, src/components/(yejin)/StudyTop.tsx, src/components/common/Header.tsx, src/components/sidebar/SideBar.tsx
=> [design] 헤더, 공지사항 부분 퍼블리싱 수정

src/app/(JH)/matching/_components/ClientMatching.tsx, src/app/(JH)/matching/_components/Interest.tsx, src/app/(JH)/matching/_components/MatchingCompleted.tsx, src/components/(JH)/matching/CircleButton.tsx, src/components/(JH)/matching/FlexContainer.tsx, src/components/(JH)/matching/MatchingFooter.tsx, src/components/common/Tab/CommonTab.tsx, src/lib/db.ts, src/utils/DBmatching.ts, src/utils/matchingreducer.ts
| 완성 이미지/GIF |
| ![image](https://github.com/Woongjin-Udemy-Pixe11/sturing/assets/124956289/f4c49667-37ab-423b-bca5-b2ae5ef1da07)  |
- [feat] 몽고 DB matching 제출함수 작성
- CSS 자잘한 부분수정
1. 컴포넌트 memo 최적화
2. 수정함수 및 컴포넌트 분리
=> [feat] mongoDB 연동 및 스키마 작성

src/app/(suwan)/my-study-main/board/task-board/write/page.tsx, src/app/(yejin)/apply/my/page.tsx, src/app/(yejin)/apply/other/page.tsx, src/app/(yejin)/study-apply/complete/page.tsx, src/app/(yejin)/study-apply/create/page.tsx, src/app/api/study-form/route.ts, src/app/api/study-member/route.ts, src/app/api/study/route.ts, src/components/common/Card.tsx, src/components/common/Complete.tsx, src/components/common/StudyCardList.tsx, src/components/common/StudyForm.tsx, src/lib/schemas/_studySchema.ts, src/lib/schemas/bookmarkSchema.ts, src/lib/schemas/studyFormSchema.ts, src/lib/schemas/studyMemberSchema.ts, src/lib/schemas/studyReviewSchema.ts, src/lib/schemas/studySchema.ts, src/types/TStudy.ts
1. study, studyForm, studyMember, studyReview, bookmark 스키마 생성
2. 카드리스트 오타수정, 스터디 타입부분 파일을 따로 빼서 정리해뒀습니다.
3. complete 공통 컴포넌트안에 있는 버튼 삭제
4. route 부분은 아직 진행중으로 간단 get,post 코드만 넣어뒀습니다.
=> [feat] 스키마 생성, 자질구레한 간단 css 코드 수정

src/auth.config.ts, src/lib/db.ts, src/lib/schemas/userSchema.ts
=> user 스키마 nickname unique 삭제, 저장시 create로 변경

src/app/(yejin)/apply/my/[id]/page.tsx, src/app/(yejin)/apply/my/page.tsx, src/app/(yejin)/apply/other/[id]/page.tsx, src/app/(yejin)/my-study-list/page.tsx, src/app/(yejin)/study-apply/create/page.tsx, src/app/api/study-form/[id]/route.ts, src/app/api/study-form/my/route.ts, src/app/api/study-form/receive/route.ts, src/app/api/study/route.ts, src/app/api/study/user/route.ts, src/app/page.tsx, src/components/(yejin)/StudyTop.tsx, src/components/(yejin)/apply/MyApply.tsx, src/components/(yejin)/apply/OtherApply.tsx, src/components/(yejin)/my-study/ApplicationList.tsx, src/components/(yejin)/my-study/StudyApplyForm.tsx, src/components/(yejin)/my-study/StudyList.tsx, src/components/(yejin)/my-study/UpcomingStudy.tsx, src/components/(yejin)/review/ReviewForm.tsx, src/components/common/StudyCardList.tsx, src/lib/actions/reviewAction.ts, src/lib/actions/studyForm.ts, src/lib/schemas/studyFormSchema.ts, src/lib/schemas/studyMemberSchema.ts, src/lib/schemas/studyReviewSchema.ts, src/lib/schemas/studySchema.ts, src/types/TStudy.ts
=> [feat] 메인(추천), 내 스터디 리스트 기능 구현(미완성)

package-lock.json, package.json, src/app/layout.tsx, src/components/(jisubin)/login/LoginModal.tsx, src/components/common/Header.tsx, src/components/sidebar/SideBar.tsx, src/components/sidebar/UserProfile.tsx, src/lib/actions/userAction.ts, src/lib/schemas/commentSchema.ts, src/store/userStore.ts
=> [feat] 로그인 자잘한 분기처리, zustand 초기세팅, comment 스키마생성

src/app/(JH)/users/[userid]/_pages/MyBookMarkList.tsx, src/app/api/bookmark/route.ts
=> [fix] 북마크 기능 오류수정

src/app/(JH)/matching/_components/ClientMatching.tsx, src/app/(JH)/users/[userid]/_pages/MyBookMarkList.tsx, src/app/api/matching/route.ts, src/lib/schemas/matchingSchema.ts, src/lib/schemas/userSchema.ts
=> [fix]매칭 다큐멘트와 유저다큐멘트 연동 및 스키마 수정

src/app/(ryukyung)/pages/SearchPart.tsx, src/app/(ryukyung)/search/page.tsx, src/components/common/SearchInput.tsx, src/components/search/CurrentSearch.tsx, src/components/search/CurrentWord.tsx, src/utils/useLocalStorage.ts
| 완성 이미지/GIF |
| ![bandicam-2024-07-09-19-57-36-010](https://github.com/Woongjin-Udemy-Pixe11/sturing/assets/124956289/04e58c7d-b570-4d2d-a8a4-5126c9e190ed)  |
- 커스텀 훅 추가
- 로컬저장소 와 상태 연동
- X버튼 클릭시 삭제
1. 각 버튼 클릭시 검색어로 이동은하지않음
=> [feat] 최근검색어 로컬스토리지 및 상태연동

src/app/(yejin)/apply/other/[id]/page.tsx, src/app/(yejin)/review/page.tsx, src/app/api/study-form/[id]/route.ts, src/app/api/study-form/other/route.ts, src/app/api/study-form/status/route.ts, src/app/api/study-member/route.ts, src/app/api/study-review/route.ts, src/app/api/study/user/route.ts, src/components/(yejin)/apply/MyApply.tsx, src/components/(yejin)/apply/MyApplyCilent.tsx, src/components/(yejin)/apply/OtherApply.tsx, src/components/(yejin)/apply/OtherApplyClient.tsx, src/components/(yejin)/my-study/ApplicationList.tsx, src/components/(yejin)/my-study/StudyList.tsx, src/components/(yejin)/my-study/StudyMember.tsx, src/components/(yejin)/review/ReviewForm.tsx, src/components/(yejin)/review/ReviewFormClient.tsx, src/lib/schemas/studyMemberSchema.ts, src/lib/schemas/studyReviewSchema.ts
- 내 스터디 종료탭에 멤버 리스트 불러와서 후기 작성 기능 구현
- 스터디 리스트 팀장/팀원 으로 참여하는 리스트 전체 출력
1. 아직 팀원 리뷰 부분 팀장제외 못했습니다
2. 후기 작성 시 작성완료로 변경처리 못함 ㅠㅠ
3. 지원서 부분 아직 처리 못했습니다
=> [feat] 스터디 리뷰 작성, 스터디 팀장/팀원 리스트 전체 출력

src/app/(JH)/matching/_components/ClientMatching.tsx, src/app/(JH)/matching/_components/Interest.tsx, src/app/(JH)/matching/_components/MatchingCompleted.tsx, src/app/(JH)/matching/_components/Mood.tsx, src/app/(JH)/matching/_components/Region.tsx, src/app/(JH)/matching/_components/Type.tsx, src/app/(JH)/matching/page.tsx, src/app/(JH)/users/[userid]/_pages/MyBookMarkList.tsx, src/app/(JH)/users/[userid]/_pages/MyPage.tsx, src/app/(JH)/users/[userid]/_pages/StudyLog.tsx, src/app/(JH)/users/[userid]/mystudylog/page.tsx, src/app/(JH)/users/[userid]/page.tsx, src/app/(ryukyung)/pages/SearchPart.tsx, src/app/api/study-member/route.ts, src/app/layout.tsx, src/components/(JH)/users/MyStudyInfo.tsx
- 마이페이지 스터디이력 추가완료
- 매칭 정보에서 유저닉네임으로 환영할수있도록 처리완료
=> [fix] 마이페이지 및 매칭 마무리

src/app/api/study-form/[id]/route.ts, src/app/api/study-form/other/route.ts, src/app/api/study/main/route.ts, src/components/(yejin)/apply/OtherApplyClient.tsx, src/components/(yejin)/my-study/ApplicationList.tsx, src/components/(yejin)/my-study/StudyList.tsx, src/components/(yejin)/my-study/UpcomingStudy.tsx, src/components/common/StudyCardList.tsx
=> [feat] 스터디 리스트 목록 수정

src/app/page.tsx
=> [feat] 메인-추천 페이지 닉네임으로 변경

src/app/(suwan)/make-study-form/[lectureId]/page.tsx, src/app/(suwan)/my-study-main/[studyId]/board/page.tsx, src/app/(suwan)/my-study-main/[studyId]/calendar/page.tsx, src/app/(suwan)/my-study-main/[studyId]/my-todo/page.tsx, src/app/(suwan)/my-study-main/[studyId]/team/page.tsx, src/app/api/lecture/[id]/route.ts, src/components/(suwan)/my-study/head/StudyInfo.tsx, src/utils/my-study-main/fetch.ts, src/utils/my-study-main/fetchStudy.ts
강의 링크 추가했어용
?data=lectureName&data=lectureURL
원하는 강의 데이터만 받을 수 있써여
=> [feat] my-study-main 헤더 정보 완료

src/app/api/study-form/[id]/route.ts, src/app/api/study-form/my/route.ts, src/app/api/study-form/status/route.ts, src/components/(yejin)/apply/MyApplyCilent.tsx, src/components/(yejin)/apply/OtherApplyClient.tsx, src/components/(yejin)/my-study/ApplicationList.tsx, src/components/(yejin)/my-study/StudyApplyForm.tsx, src/components/common/StudyCardList.tsx, src/components/common/modal/DefaultModal.tsx, src/lib/schemas/studySchema.ts
- 스터디 지원서(열람, 미열람, 수락) 기능 구현
- 공통 모달 예/아니오 버튼 함수 추가 
`<DefaultModal
onConfirm={onConfirm}
onCancel={onCancel}
/>`
-  카드 리스트 날짜 형식 변경
-  스터디 스키마 studyJoinMember default = 0 에서 1로 변경
=> [feat] 스터디 지원서 기능 구현 완료, 공통 모달 수정

src/components/search/BottomSheetFilter.tsx, src/components/search/filter/CheckBox.tsx, src/components/search/filter/Field.tsx, src/utils/filterReducer.ts
feat: 새로운 기능 추가
fix: 버그 수정
docs: 문서 수정
design: 퍼블리싱, CSS 등 사용자 UI 디자인 변경
style: 들여쓰기, 세미콜론 등 코드 스타일 변경
refactor: 코드 리팩토링
chore: 외부 라이브러리 임포트 등의 작업 완료
comment: 필요한 주석 추가 및 변경
rename: 파일 혹은 폴더명을 수정하거나 옮기는 작업만 한 경우
remove: 파일을 삭제하는 작업만 한 경우
| 완성 이미지/GIF |
-
1.
=> [feat] 필터기능 디자인선택완료

src/app/(suwan)/make-study-form/[lectureId]/page.tsx
=> [fix] 스터디 개설 폼 에러 해결

src/app/(suwan)/make-study-form/_component/StudyInfoForm.tsx
=> [fix] 이미지 기본값 수정

src/app/(jisubin)/study-detail/[id]/layout.tsx
=> [feat] 스터디 지원하기 버튼 link 연결

src/app/(suwan)/make-study-form/_component/CollectStudyClient.tsx, src/app/(suwan)/make-study-form/_component/StudyTeammateForm.tsx, src/app/api/study/route.ts, src/utils/study/studyUtils.ts
=> [feat] 스터디 개설시 리더  멤버 추가

src/app/(yejin)/study-apply/[id]/page.tsx, src/app/(yejin)/study-apply/complete/page.tsx, src/components/(yejin)/my-study/StudyApplyForm.tsx
=> [fix] 스터디 지원서 링크 연결

src/app/(JH)/matching/page.tsx, src/app/(ryukyung)/search/loading.tsx, src/app/(ryukyung)/search/result/page.tsx, src/app/loading.tsx
=> [feat] 로딩 컴포넌트 추가합니다.

src/app/api/mypage/route.ts, src/lib/schemas/studySchema.ts
- 스터디 스키마 소프트삭제 필드 추가
- 회원탈퇴시 스터디 완전삭제에서 소프트삭제로 변경
1.
=> [fix] 스터디 스키마수정(isDeleted):스터디 소프트삭제 / route 수정

src/app/(JH)/users/[userid]/_pages/MyPageDetail.tsx, src/components/(JH)/users/MyPageProfileCard.tsx, src/components/(JH)/users/MyStudyInfo.tsx, src/components/(JH)/users/UserDetailButton.tsx, src/components/(suwan)/make-study-form/pages/Completed.tsx
- 마이페이지, > 버튼 클릭시 유저정보수정
- 마이페이지, 매칭정보 클릭시->/matching 이동
- 매칭정보없을시, 매칭하러가시겠습니까? 버튼추가
1.
=> [fix] mypage 정보수정, ">" 아이콘클릭시 내정보수정 ,매칭정보수정시 매칭으로

src/app/(ryukyung)/pages/SearchPart.tsx, src/components/search/CurrentSearch.tsx, src/utils/useLocalStorage.ts
- 로컬 스토리지 전체삭제기능
- Custom Hook 수정
1.
=> [feat] 로컬스토리지 전체삭제

src/app/api/mypage/route.ts, src/components/(JH)/users/UserDetailInfo.tsx, src/utils/updateNicname.ts
=> [fix] 마이페이지 캐시처리완료

src/app/(JH)/users/[userid]/detail/page.tsx, src/app/layout.tsx, src/app/page.tsx, src/lib/actions/userAction.ts, src/utils/getSessions.ts
- 마이페이지 닉네임수정시 getSession으로 얻는 닉네임 변경
1.
=> [feat] 닉네임 변경시 session 닉네임변경

src/app/(jisubin)/lecture-detail/[id]/layout.tsx, src/app/(jisubin)/study-detail/[id]/layout.tsx, src/app/api/study-detail/bookmark/route.ts, src/components/(jisubin)/lectureStudyDetail/BookmarkBtnNavigationBar.tsx, src/utils/study-detail/bookmarkUtils.ts
| 완성 이미지/GIF |
- 스터디 상세페이지에 사용되는 컴포넌트 재사용할 수 있도록 props 명 수정
- route.ts 경로 수정 필요.. 지금 api/study-detail/bookmark/route.ts를 가져다 쓰고 있는데 공통 북마크 폴더로 빼서 사용해야 할듯
=> [feat] 강의 상세페이지 북마크 get, post, update

src/app/api/study-form/route.ts, src/components/common/Header.tsx
=> [fix] 헤더 사람아이콘 클릭시 로그인상태에서 로그인 모달 뜨는 문제 해결

src/app/(jisubin)/study-detail/_components/StudyComment.tsx, src/app/(jisubin)/study-detail/_components/StudyComments.tsx, src/lib/actions/commentAction.ts
| 완성 이미지/GIF |
| <img width="250" alt="image" src="https://github.com/user-attachments/assets/8adf76d4-105a-4006-84da-65e822917ca6"> |
- ":" 버튼 클릭시 수정,삭제 드롭다운 출력
- 수정, 삭제 기능
- 드롭다운 애니메이션 추가 필요
- 수정시 수정시간 즉각적으로 바로 보여지게 수정 필요(클라이언트-서버 컴포넌트 구성..에 대한 고민..)
=> [feat] 스터디 상세페이지 댓글 수정, 삭제

src/components/common/StudyCardList.tsx
=> [feat] Card 컴포넌트 Link 연결

src/components/common/Tab/CommonTab.tsx, src/components/search/BottomSheetFilter.tsx
=> [fix] 지역필터 검색하기(간단)

src/components/(jisubin)/lectureStudyDetail/BookmarkBtnNavigationBar.tsx, src/components/common/Card.tsx, src/components/common/StudyCardList.tsx, src/types/TStudy.ts
| 로그인 | 비로그인 |
| :-------------: | :-------------:|
| <img width="250" alt="image" src="https://github.com/user-attachments/assets/743abc6b-0b62-42bc-9184-2e1bf248b6d2"> | <img width="250" alt="image" src="https://github.com/user-attachments/assets/f58cc641-5c7c-462c-93e8-07a5a1c2ef6e">|
- 스터디 카드에서 현재 유저가 북마크한 스터디면 북마크 표시
- 비어있는 북마크 버튼 클릭시 북마크 post
- 채워져있는 북마크 버튼 클릭시 북마크 상태 false로 update
- 로그인 상태일때만 북마크 버튼 표시
=> [feat] study card 북마크 get, post, update, 로그인했을때만 북마크 표시되도록 

src/components/common/Card.tsx
=> [feat] 로그인 상태일때만 bookmark fetch 하도록 수정

package-lock.json, package.json, src/app/(JH)/users/[userid]/_pages/MyPageDetail.tsx, src/app/api/profileimage/route.ts, src/components/(JH)/users/EditProfileImage.tsx, src/lib/supabaseClient.ts, src/utils/profileUpdate.ts
- 프로필 이미지 수정가능완료
- 마이페이지 css 수정안함.
1.
=> [feat] 프로필이미지 수정완성

next.config.mjs
=> [feat] next.config.js에 이미지 외부주소(supabase) 설정

src/components/(yejin)/apply/MyApplyCilent.tsx, src/components/(yejin)/apply/OtherApplyClient.tsx, src/components/(yejin)/my-study/ApplicationList.tsx
=> [fix] 지원서 받는 시간 한국시간으로 변경

src/app/(jisubin)/study-detail/_components/CommentForm.tsx, src/app/(jisubin)/study-detail/_components/StudyComment.tsx, src/app/(suwan)/my-study-main/[studyId]/board/_component/BoardComment.tsx, src/app/(suwan)/my-study-main/[studyId]/board/_component/Comment.tsx, src/app/(suwan)/my-study-main/[studyId]/board/task-board/[taskId]/page.tsx, src/app/api/study-board/comment/route.ts, src/types/TStudyBoard.ts, src/utils/my-study-main/fetch.ts
| 완성 이미지/GIF |
|![image](https://github.com/user-attachments/assets/92704867-176f-48ef-9c78-440771d809c5)  |
- 댓글 수정/삭제 구현
- 좋아요는 우선 지워뒀습니당...
- 팀장 여부 표시, 좋아요 등은.. 추후... ?
=> [feat] my-study-main 게시판 댓글 수정/삭제, 유저이미지 import

src/app/(suwan)/my-study-main/[studyId]/board/_component/NoticeForm.tsx, src/app/(suwan)/my-study-main/[studyId]/board/notice-board/[noticeId]/eddit/page.tsx, src/app/(suwan)/my-study-main/[studyId]/board/notice-board/[noticeId]/page.tsx, src/app/(suwan)/my-study-main/[studyId]/team/page.tsx, src/components/(suwan)/my-study/team/Gallery.tsx, src/components/(suwan)/my-study/team/component/AttendanceCheck.tsx
=> [feat] 이미지, 수정및 팀페이지 이미지보여주기 완성

src/app/(suwan)/my-study-main/[studyId]/board/_component/NoticeForm.tsx
feat: 새로운 기능 추가
fix: 버그 수정
docs: 문서 수정
design: 퍼블리싱, CSS 등 사용자 UI 디자인 변경
style: 들여쓰기, 세미콜론 등 코드 스타일 변경
refactor: 코드 리팩토링
chore: 외부 라이브러리 임포트 등의 작업 완료
comment: 필요한 주석 추가 및 변경
rename: 파일 혹은 폴더명을 수정하거나 옮기는 작업만 한 경우
remove: 파일을 삭제하는 작업만 한 경우
-
1.
=> [fix] 이미지 수정 완료

src/app/(ryukyung)/pages/SearchPart.tsx, src/components/sidebar/SideBarToggle.tsx, src/constant/searchLabelList.ts
=> [fix] 사이드바 링크분야 수정완료

src/auth.config.ts
- authconfig 수정, 맨처음 url 태우는 코드 삭제
- search 로그인안할시 callback 태워서 접속불가 상태 해결
- 전체적인 권한설정필요
1.
=> [fix] authconfig.ts 수정. search 로그인안해도 들어가짐

src/components/common/SearchInput.tsx
=> [design] 검색엔진 focus시 아웃라인 css제거

src/app/(ryukyung)/pages/SearchPart.tsx, src/app/(ryukyung)/search/result/page.tsx, src/utils/useLocalStorage.ts
- Search 함수 및 로컬스토리지 함수 최적화
1.
=> [fix] Search 함수 및 로컬스토리지 함수 최적화

src/app/(jisubin)/study-detail/_components/CommentForm.tsx, src/app/api/mypage/route.ts, src/app/page.tsx, src/components/(jisubin)/lectureStudyDetail/BookmarkBtnNavigationBar.tsx
| 완성 이미지/GIF |
- 비로그인시 스터디상세, 강의상세 북마크오류 수정
- 스터디상세 비로그인상태에서 댓글작성시 alert 경고문구
1.
=> [fix] 비로그인시 북마크에러, 스터디상세페이지 댓글작성시 alert 알림

src/app/(jisubin)/study-detail/[id]/layout.tsx, src/app/(jisubin)/study-detail/[id]/page.tsx, src/app/(jisubin)/study-detail/_components/StudyMood.tsx, src/app/(jisubin)/study-detail/_components/StudyTeamMembers.tsx, src/components/common/Card.tsx, src/components/common/StudyCardList.tsx, src/components/search/RecommendSearch.tsx, src/constant/recommendSearchList.ts
- 초기값 문자열로인한 타입에러 수정(lecture 정보)
- 스터디 상세정보 이모지 Image 컴포넌트로 넓이높이 경고메세지,->img 태그로변경
- Image 태그 fill 속성 및 sizes 추가
- 검색 페이지 추천검색어 링크연결
- 스터디 상세정보 , 스터디배경이미지 사이즈확대시 여러개보이던 css 수정
1. 검색페이지 추천검색어로 검색했을때 나올만한 스터디 만들면좋을듯
=> [fix] 전체적인 css 및 링크연결 추가

src/app/(jisubin)/study-detail/_components/StudyComment.tsx
=> [fix] 스터디 상세페이지 css 수정

src/app/(JH)/matching/_components/ClientMatching.tsx, src/app/(JH)/matching/_components/Field.tsx, src/app/(JH)/matching/_components/MatchingCompleted.tsx, src/app/(JH)/matching/_components/Type.tsx, src/app/(JH)/users/[userid]/detail/delete/page.tsx, src/app/api/study/main/route.ts, src/app/api/study/user/route.ts, src/app/globals.css, src/app/page.tsx, src/components/(JH)/matching/MatchingContainer.tsx, src/components/(JH)/matching/MatchingFooter.tsx, src/components/(JH)/matching/SelectMatching.tsx, src/components/(JH)/users/AccountCancelModal.tsx, src/components/(JH)/users/DeleteModal.tsx, src/components/(JH)/users/MyPageLabel.tsx, src/components/(JH)/users/MyPageProfileCard.tsx, src/components/(JH)/users/MyStudyInfo.tsx, src/components/(JH)/users/UserDetailButton.tsx, src/components/(yejin)/my-study/ApplicationList.tsx, src/components/common/Card.tsx, src/components/common/SectionNavigator.tsx, src/components/common/Tab/CommonTab.tsx, src/components/search/BottomSheetFilter.tsx, src/components/search/FilterBar.tsx
- 매칭, 마이페이지 css 수정했습니다
- 다가오는 스터디 최신순으로 수정했습니다
- 추천 페이지 링크 연결 해제했습니다
1. 스터디 상세 , 강의 상세 못해서 얼른 해보겠습니다 ㅠㅜ
2.  env 파일 NEXT_PUBLIC_LOCAL_URL=http://localhost:3000
=> [design] 매칭, 마이페이지 css 수정

src/app/(JH)/users/[userid]/_pages/MyPageDetail.tsx, src/app/(ryukyung)/search/page.tsx, src/components/common/MatchingBanner.tsx, src/components/search/CurrentStudy.tsx, src/components/sidebar/SideBarToggle.tsx, src/components/sidebar/UserProfile.tsx
- 서치페이지 북마크 유저아이디 추가
- sidebar토글 key값추가
- form 태그 상위요소 div로 변경
1.
=> [fix]jh-bug

src/app/(suwan)/my-study-main/[studyId]/board/_component/TaskBoardList.tsx, src/app/(suwan)/my-study-main/[studyId]/board/_component/TaskDetail.tsx, src/app/(suwan)/my-study-main/[studyId]/board/_component/TaskInfo.tsx, src/app/(suwan)/my-study-main/[studyId]/board/page.tsx
=> [fix] img 에러 해결

src/app/(JH)/users/[userid]/_pages/MyBookMarkList.tsx, src/app/(ryukyung)/search/result/page.tsx, src/components/search/BottomSheetFilter.tsx, src/components/search/GrayFullLink.tsx, src/components/search/LectureList.tsx, src/components/search/StudyList.tsx, src/components/search/TabAll.tsx, src/components/search/TabBarBlue.tsx, src/components/search/TabContainer.tsx, src/components/sidebar/UserProfile.tsx
=> [fix] 검색 후 스터디,강의 전체보기 링크 연결

src/app/(suwan)/my-study-main/[studyId]/board/_component/BoardComment.tsx, src/app/(suwan)/my-study-main/[studyId]/board/_component/Comment.tsx, src/app/(suwan)/my-study-main/[studyId]/board/_component/EmojiSelectBtn.tsx, src/app/(suwan)/my-study-main/[studyId]/board/_component/TaskBoardList.tsx, src/app/(suwan)/my-study-main/[studyId]/board/_component/TaskDetail.tsx, src/app/(suwan)/my-study-main/[studyId]/board/_component/TaskInfo.tsx, src/app/(suwan)/my-study-main/[studyId]/board/notice-board/[noticeId]/page.tsx, src/app/(suwan)/my-study-main/[studyId]/board/page.tsx, src/app/(suwan)/my-study-main/[studyId]/board/task-board/[taskId]/page.tsx, src/app/(suwan)/my-study-main/[studyId]/team/page.tsx, src/app/api/study-board/route.ts, src/components/(suwan)/my-study/team/Gallery.tsx, src/components/(suwan)/my-study/team/Percent.tsx, src/components/(suwan)/my-study/team/TeamTodo.tsx, src/utils/my-study-main/fetch.ts
=> [feat] 조회수 기능, 팁별 투두 확인

src/app/(jisubin)/lecture-detail/[id]/layout.tsx, src/app/(jisubin)/study-detail/[id]/layout.tsx, src/components/(jisubin)/lectureStudyDetail/BookmarkBtnNavigationBar.tsx
=> [fix] 강의 - 스터디 개설 / 스터디 - 스터디 지원 버튼 구분

src/app/(JH)/matching/_components/ClientMatching.tsx, src/app/(JH)/matching/_components/Field.tsx, src/app/(JH)/matching/_components/Interest.tsx, src/app/(JH)/matching/_components/MatchingCompleted.tsx, src/app/(JH)/matching/_components/Mood.tsx, src/app/(JH)/matching/_components/Region.tsx, src/app/(JH)/matching/_components/Type.tsx, src/app/(JH)/users/[userid]/_pages/MyBookMarkList.tsx, src/app/(JH)/users/[userid]/_pages/MyPage.tsx, src/app/(JH)/users/[userid]/_pages/MyPageDetail.tsx, src/app/(JH)/users/[userid]/_pages/MyStudyReviewList.tsx, src/app/(JH)/users/[userid]/_pages/StudyLog.tsx, src/app/(JH)/users/[userid]/detail/delete/page.tsx, src/app/(JH)/users/[userid]/detail/page.tsx, src/app/(JH)/users/[userid]/mystudylog/page.tsx, src/app/(JH)/users/[userid]/mystudyreview/page.tsx, src/app/api/study-review/route.ts, src/components/(JH)/users/DeleteModal.tsx, src/components/(JH)/users/StudyReviewCard.tsx, src/types/TSession.ts, src/types/TStudyInfo.ts, src/types/TStudyReview.ts, src/types/TgetUserStudy.ts, src/types/TmypageDetail.ts
=> [refactor] 매칭페이지, 유저페이지 타입및 props 정의

src/app/(ryukyung)/search/result/_components/BackSearchBar.tsx, src/app/(ryukyung)/search/result/page.tsx
=> [fix] 검색 결과 페이지 뒤로가기 버튼 기능 추가

src/app/(JH)/users/[userid]/_pages/StudyLog.tsx, src/app/(jisubin)/lecture-detail/[id]/layout.tsx, src/app/(jisubin)/lecture-detail/[id]/page.tsx, src/app/(jisubin)/lecture-detail/_components/LectureRating.tsx, src/app/(jisubin)/lecture-detail/_components/LectureStudy.tsx, src/app/(jisubin)/study-detail/[id]/layout.tsx, src/app/(jisubin)/study-detail/[id]/page.tsx, src/app/(jisubin)/study-detail/_components/StudyComments.tsx, src/app/(jisubin)/study-detail/_components/StudyTeamMembers.tsx, src/app/(ryukyung)/search/loading.tsx, src/app/loading.tsx, src/components/common/StudyCardList.tsx, src/components/search/CurrentSearch.tsx, src/components/search/CurrentStudy.tsx, src/components/search/CurrentWord.tsx, src/types/TLecture.ts, src/types/TStudyComment.ts, src/types/TStudyMember.ts, tsconfig.json
- study-detail 타입수정
- lecture-detail 타입수정
- lecture-detail 카드컴포넌트 클릭시 스터디로 링크이동
- Loading Componet css 중앙으로 오게 수정
- SearchPart type 수정
1.
=> [fix] type 수정 및 , Loading 컴포넌트 수정

src/app/(JH)/users/[userid]/page.tsx, src/app/(yejin)/apply/my/[id]/page.tsx, src/components/(yejin)/apply/MyApply.tsx, src/types/TStudyApply.ts
=> [fix]  유저페이지에서 유저정보 내려주는 id, prams 값으로변경

src/components/common/Card.tsx, tailwind.config.ts
=> [design] 북마크 그림자 추가

src/middleware.ts
=> [feat] middleware 변경

src/app/(suwan)/my-study-main/[studyId]/_components/Calendar.tsx
=> [design] 일정 있는 날짜 선택시 css 적용

src/app/api/study-todo/route.ts
=> [fix] PATCH return 수정

src/app/(JH)/users/[userid]/page.tsx, src/app/(yejin)/my-study-list/page.tsx
=> [fix] getUserStuies 경로 수정

src/app/(JH)/users/[userid]/_pages/StudyLog.tsx
=> [fix] 스터디 로그 import 링크 변경

src/app/(suwan)/my-study-main/[studyId]/my-todo/_components/Todos.tsx, src/app/(suwan)/my-study-main/[studyId]/my-todo/page.tsx, src/app/api/study-todo/route.ts, src/components/(suwan)/my-study/head/Tabar.tsx, src/components/(suwan)/my-study/team/Percent.tsx, src/lib/actions/todoAction.ts
| 완성 이미지/GIF |
| <img width="379" alt="스크린샷 2024-07-30 오전 12 45 24" src="https://github.com/user-attachments/assets/063c05ab-185d-40fd-a2e5-7656f5c6584b"> |
- 에러 이것저것 수정했어요
- 출석을 잘 하면 상위에 올라와요
=> [feat] 에러수정, 출석

src/components/(suwan)/my-study/team/Attend.tsx, src/components/(suwan)/my-study/team/TeamTodo.tsx, src/components/(suwan)/my-study/team/component/AttendanceCheck.tsx, src/components/common/ScrollableContainer.tsx, src/components/main/SearchLabelList.tsx, src/components/main/UserCardList.tsx
=> [design] 스크롤바 적용

src/app/(jisubin)/lecture-detail/[id]/layout.tsx, src/app/(jisubin)/study-detail/[id]/layout.tsx, src/app/globals.css, src/components/(jisubin)/lectureStudyDetail/BookmarkBtnNavigationBar.tsx, src/components/common/Header.tsx
| 완성 이미지/GIF |
| ![스크린샷 2024-07-31 오전 1 29 41](https://github.com/user-attachments/assets/c1e4ac38-c0a5-4936-9e21-78a01d13dff5)|
- 고정 잘 해씁니다
=> [design] 헤더랑 버튼 고정했습니다

src/app/(jisubin)/study-detail/[id]/layout.tsx, src/app/(jisubin)/study-detail/[id]/page.tsx, src/components/common/Header.tsx, src/components/sidebar/SideBar.tsx
=> [fix] 사이드바, 댓글 가려짐

src/auth.ts, src/components/(JH)/Ismatching.tsx, src/components/common/Card.tsx
- 매칭시 리다이렉트 로그인유무에따라 잘못되던에러 수정
1.
=> [fix] 매칭시 리다이렉트오류수정

src/components/common/Tab/CommonTab.tsx, src/components/common/Tab/FilterTab.tsx, src/components/common/label/SizeUpLabel.tsx
| 완성 이미지/GIF |
| <img width="365" alt="스크린샷 2024-07-31 오후 3 25 22" src="https://github.com/user-attachments/assets/cf8bfc9f-e884-4eb0-8ae3-7b2b2d9bd8d3">|
=> [design] 지역필터 css 수정
